# name of station
name: my-station

# supported readers
rfid: true
barcode: true

# data access
sparql_endpoint:   http://localhost:8890/sparql
default_graph:     http://example.com/books
similarity_graph:  http://data.deichman.no/noeSomLigner
resource_prefix:   http://example.com/resource/
book_status_api:   http://bibsyst/???????
department:      "voksenavdelingen"
novelist:
  profile: profile-id
  password: secret

# apperance
theme_color: 'rgba(230,87,64,1)'

# leftbar
leftbar_image: false  # set to true to override leftbar css with image 'img/leftpar.png'
leftbar_color: 'rgba(230,87,64,1)' # set opacity (last digit) to 0 to remove leftbar

# recipients of statistics email reports
email:
  daily:
    - example1@example.com
  weekly:
    - example1@example.com
    - example2@example.com
  monthly:
    - example3@example.com

smtp:
  starttls: true
  host: smtp.gmail.com
  port: 587
  domain: deichman.no      # 'your.domain.com' for GoogleApps
  authentication: :plain  # false, :plain or :login 
  username: username
  password: password

error_report:
  display: ':0.0' # unix DISPLAY env for screenshot
  emails:
    - example1@example.com
