# supported readers
rfid: true    
barcode: true

# data access
sparql_endpoint: http://localhost:8890/sparql
default_graph:   http://example.com/books
resource_prefix: http://example.com/resource/
book_status_api: http://bibsyst/???????
department:      "voksenavdelingen"

# apperance
theme_color: 'rgba(230,87,64,1)' 

# leftbar
leftbar_image: false  # set to true to override leftbar css with image 'img/leftpar.png'
leftbar_color: 'rgba(230,87,64,1)' # set opacity (last digit) to 0 to remove leftbar
