# book reader
rfid: true       # set to false to use barcode scanner

# data access
sparql_endpoint: http://localhost:8890/sparql
deafult_graph:   http://example.com/books
book_status_api: http://bibsyst/???????
department:      "voksenavdelingen"

# apperance
theme_color: 'rgba(230,87,64,0)' 

# leftbar
leftbar_image: false  # set to true to override leftbar css with image 'img/leftpar.png'
leftbar_color: 'rgba(230,87,64,0)' # set opacity (last digit) to 0 to remove leftbar
